server:
  port: 8091
  tomcat:
    connection-timeout: 90000
    max-threads: 200 # Ajusta el número de threads disponibles
  servlet:
    session:
      timeout: 5m
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000 # Timeout de conexión en milisegundos
        response-timeout: 300000 # Timeout de respuesta en milisegundos (5 minutos)
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  devtools:
    restart:
      enable: false
  mvc:
    async:
      request-timeout: 600000
  codec:
    max-in-memory-size: 60MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

api:
  bpc-scrapping-provider:
    url: ${BPC_SCRAPPING_PROVIDER_URL}
  credit-decision-engine:
    url: ${CREDIT_ENGINE_URL}
  buro-experto:
    url: ${BURO_EXPERTO_URL}
    user-id: ${BURO_EXPERTO_USERID}
    user-name: ${BURO_EXPERTO_USERNAME}
  bpc-crm:
    url: ${BPC_CRM_URL}
  bpc-parameter:
    url: ${BPC_PARAMETER_URL}
  bpc-synchronizer:
    url: ${BPC_SYNCHRONIZER_URL}

convertapi:
  secretKey: ${CONVERTAPI_KEY}

aws:
  accessKeyId: ${AWS_ACCESSKEYID}
  secretKey: ${AWS_SECRETKEY}
  presignedUrl:
    expiration: ${AWS_PRESIGNED_URL_DURATION}
  bucketName: ${BUCKET_NAME}

as2:
  sistema: ${AS2_SISTEMA}
  nombreUsuario: ${AS2_NOMBRE_USUARIO}
  clave: ${AS2_CLAVE}
  rol: ${AS2_ROL}
  url: ${AS2_BASE_URL}

ado:
  url: ${ADO_BASE_URL}
  apiKey: ${ADO_API_KEY}
  returnDocuments: ${ADO_RETURN_DOCUMENTS}
  returnVideoLiveness: ${ADO_VIDEO_LIVENESS}

equifax:
  usuario: ${EQUIFAX_USUARIO}
  clave: ${EQUIFAX_CLAVE}

power-automate:
  base-url: ${PA_BASE_URL}
  path: ${PA_PATH}
  api-version: ${PA_API_VERSION}
  sp: ${PA_SP}
  sv: ${PA_SV}
  sig: ${PA_SIG}

bot:
  afiliacion:
    durationMilis: ${AFILIACION_TIMEOUT_MILIS}
  fjudicial:
    durationMilis: ${FJUDICIAL_TIMEOUT_MILIS}
  sri:
    durationMilis: ${SRI_TIMEOUT_MILIS}
