server:
  port: 8071

spring:
  application:
    name: bpc-scheluder

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


api:
  bpc-credit-engine:
    url: http://bpc-credit-engine
  bpc-parameter:
    url: http://bpc-parameter/credit-engine/api/v1/parameter/policy/find
