server:
  port: 8094
spring:
  r2dbc:
    url: r2dbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?sslMode=require
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    pool:
      max-size: 10
      initial-size: 2
      validation-query: "SELECT 1"
      max-idle-time: 30s
      max-acquire-time: 30s
      max-create-connection-time: 30s
  data:
    r2dbc:
      repositories:
        enabled: true
  devtools:
    restart:
      enable: false
  mvc:
    async:
      request-timeout: 360000
  codec:
    max-in-memory-size: 5MB
  webflux:
    session:
      timeout: 120s
    netty:
      idle-timeout: 120s
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
