server:
  port: 8086
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  devtools:
    restart:
      enable: false
  mvc:
    async:
      request-timeout: 360000
  codec:
    max-in-memory-size: 5MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
