server:
  port: 8096
spring:
  main:
    allow-bean-definition-overriding: false
  r2dbc:
    url: r2dbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  data:
    r2dbc:
      repositories:
        enabled: true
  devtools:
    restart:
      enable: false
  mvc:
    async:
      request-timeout: 360000
  codec:
    max-in-memory-size: 5MB
  webflux:
    session:
      timeout: 120s
    netty:
      idle-timeout: 120s

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

api:
  bpc-management:
    url: lb://bpc-security/api/v1/management
