server:
  port: 9090
spring:
  application:
    name: bpc-model-decision
  cloud:
    discovery:
      enable: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  devtools:
    restart:
      enable: false 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

camunda:
  bpm:
    admin-user:
      #id: Administrator
      #password: 20Decision24
      id: ${CAMUNDA_ADMIN_ID}
      password: ${CAMUNDA_ADMIN_PASSWORD}
    generic-properties:
      properties:
        historyTimeToLive: P1D

logging:
  level:
    root: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
