server:
  port: 9090
spring:
  profiles:
    active: dev,test,prod
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  devtools:
    restart:
      enable: false 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
  cloud:
    discovery:
      enabled: true
#EurekaClient
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
          defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

camunda:
  bpm:
    admin-user:
      #id: Administrator
      #password: 20Decision24
      id: ${CAMUNDA_ADMIN_ID}
      password: ${CAMUNDA_ADMIN_PASSWORD}
    generic-properties:
      properties:
        historyTimeToLive: P1D

logging:
  level:
    root: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

bot:
  webdatos:
    durationMilis: ${WEBDATOS_TIMEOUT_MILIS}
  fjudicial:
    durationMilis: ${FJUDICIAL_TIMEOUT_MILIS}
  sri:
    durationMilis: ${SRI_TIMEOUT_MILIS}
